global:
  resolve_timeout: 5m
route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'default'
    email_configs:
      - to: 'sirine.makni@supcom.tn'
        from: 'maknisirine52@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'maknisirine52@gmail.com'
        auth_password: 'vupiggnamiabvipg'
        auth_identity: 'maknisirine52@gmail.com'
        require_tls: true
