all:
  children:
    webservers:
      hosts:
        web-staging:
          ansible_host: 192.168.56.30
          ansible_user: vagrant
      vars:
        monitoring_role: target
        service_type: web
        prometheus_local: true

    databases:
      hosts:
        db-staging:
          ansible_host: 192.168.56.31
          ansible_user: vagrant
      vars:
        monitoring_role: target
        service_type: database
        prometheus_local: true

    staging:
      children:
        webservers:
        databases:
      vars:
        deployment_env: staging
        alert_thresholds:
          cpu: 85
          memory: 90
          disk: 85