global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'federation-control'
    region: 'local'

rule_files:
  - "alert_rules.yml"
  - "federation_alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

scrape_configs:
  # Scraping local monitoring stack
  - job_name: 'prometheus-federator'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter-control'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor-control'
    static_configs:
      - targets: ['cadvisor:8080']

  # Federation depuis tous les Prometheus locaux
  - job_name: 'federation-web-prod-01'
    scrape_interval: 60s
    scrape_timeout: 50s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~"prometheus|node-exporter|cadvisor"}'
        - '{__name__=~"up|node_load1|node_memory_MemAvailable_bytes|node_filesystem_free_bytes"}'
        - '{__name__=~"container_cpu_usage_seconds_total|container_memory_usage_bytes"}'
    static_configs:
      - targets:
          - '192.168.56.20:9090'
        labels:
          federated_from: 'web-prod-01'
          environment: 'production'
          service_type: 'web'
  - job_name: 'federation-web-prod-02'
    scrape_interval: 60s
    scrape_timeout: 50s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~"prometheus|node-exporter|cadvisor"}'
        - '{__name__=~"up|node_load1|node_memory_MemAvailable_bytes|node_filesystem_free_bytes"}'
        - '{__name__=~"container_cpu_usage_seconds_total|container_memory_usage_bytes"}'
    static_configs:
      - targets:
          - '192.168.56.21:9090'
        labels:
          federated_from: 'web-prod-02'
          environment: 'production'
          service_type: 'web'
  - job_name: 'federation-db-prod'
    scrape_interval: 60s
    scrape_timeout: 50s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~"prometheus|node-exporter|cadvisor"}'
        - '{__name__=~"up|node_load1|node_memory_MemAvailable_bytes|node_filesystem_free_bytes"}'
        - '{__name__=~"container_cpu_usage_seconds_total|container_memory_usage_bytes"}'
    static_configs:
      - targets:
          - '192.168.56.25:9090'
        labels:
          federated_from: 'db-prod'
          environment: 'production'
          service_type: 'database'
  - job_name: 'federation-nginx-prod'
    scrape_interval: 60s
    scrape_timeout: 50s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~"prometheus|node-exporter|cadvisor"}'
        - '{__name__=~"up|node_load1|node_memory_MemAvailable_bytes|node_filesystem_free_bytes"}'
        - '{__name__=~"container_cpu_usage_seconds_total|container_memory_usage_bytes"}'
    static_configs:
      - targets:
          - '192.168.56.26:9090'
        labels:
          federated_from: 'nginx-prod'
          environment: 'production'
          service_type: 'proxy'

