---
- name: Supprimer anciens paquets Docker et Compose
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-plugin
      - podman-docker
      - containerd
      - runc
      - containerd.io
    state: absent
    purge: yes
    autoremove: yes
  become: yes

- name: Installer dépendances pour dépôt Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: yes

- name: Créer répertoire pour clés GPG Docker
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Télécharger clé GPG Docker et la convertir
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: yes

- name: Assurer les permissions correctes de la clé GPG
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  become: yes

- name: Ajouter dépôt Docker officiel
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes


- name: Installer Docker et Docker Compose v2
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes

- name: Activer et démarrer le service Docker
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
