---


- name: Deploy federation monitoring on control node
  hosts: control
  gather_facts: yes
  vars_files:
    - ../vault/secrets.yml
    - ../group_vars/all.yml
  roles:
    - prometheus_federator
  
  post_tasks:
    - name: Collect remote prometheus instances info
      set_fact:
        remote_instances: "{{ remote_instances | default([]) + [{'host': item, 'ip': hostvars[item]['ansible_host'], 'port': hostvars[item]['prometheus_local_port'] | default(9090)}] }}"
      loop: "{{ groups['all'] }}"
      when: 
        - item != inventory_hostname 
        - hostvars[item]['prometheus_local'] is defined
        - hostvars[item]['prometheus_local'] | bool

    - name: Display remote prometheus instances
      debug:
        msg: "{{ item.host }}: http://{{ item.ip }}:{{ item.port }}"
      loop: "{{ remote_instances | default([]) }}"
      when: remote_instances is defined

    - name: Display federation summary
      debug:
        msg:
          - "=== Federation Setup Complete ==="
          - "Total federated instances: {{ (remote_instances | default([])) | length }}"
          - "Federation status: {{ 'SUCCESS' if federation_targets is succeeded else 'FAILED' }}"