all:
  children:
    control:
      hosts:
        desktop-vm:
          ansible_host: localhost
          ansible_user: sirine
          ansible_connection: local
      vars:
        monitoring_role: federator
        prometheus_federation: true
        prometheus_local: false
        
    webservers:
      hosts:
        web-dev:
          ansible_host: 192.168.56.40
          ansible_user: vagrant
      vars:
        monitoring_role: target
        service_type: web
        prometheus_local: true

    development:
      children:
        webservers:
      vars:
        deployment_env: development
        alert_thresholds:
          cpu: 90
          memory: 95
          disk: 80