all:
  children:
    desktop:
      hosts:
        desktop-vm:
          ansible_host: localhost
          ansible_user: sirine
          ansible_connection: local


      vars:
        deployment_env: development
        monitoring_role: desktop

