- name: restart federation prometheus
  become: true
  
  shell: |
    cd {{ project_dir }}
    docker compose restart prometheus
  register: federation_restart_result
  failed_when: federation_restart_result.rc != 0