all:
  children:
    control:
      hosts:
        desktop-vm:
          ansible_host: localhost
          ansible_user: sirine
          ansible_connection: local
      vars:
        monitoring_role: federator
        prometheus_federation: true
        prometheus_local: false

    webservers:
      hosts:
        web-prod-01:
          ansible_host: 192.168.56.20
          ansible_user: vagrant
        web-prod-02:
          ansible_host: 192.168.56.21
          ansible_user: vagrant
      vars:
        monitoring_role: target
        service_type: web
        prometheus_local: true
        docker_services:
          - name: "nginx"
            port: 80
            monitored: true
          - name: "nodejs-app"
            port: 3000
            monitored: true

    databases:
      hosts:
        db-prod:
          ansible_host: 192.168.56.25
          ansible_user: vagrant
      vars:
        monitoring_role: target
        service_type: database
        prometheus_local: true
        docker_services:
          - name: "postgresql"
            port: 5432
            monitored: true
          - name: "redis"
            port: 6379
            monitored: true

    proxies:
      hosts:
        nginx-prod:
          ansible_host: 192.168.56.26
          ansible_user: vagrant
          proxy_type: "nginx"
      vars:
        monitoring_role: target
        service_type: proxy
        prometheus_local: true
        docker_services:
          - name: "nginx-lb"
            port: 80
            monitored: true
          - name: "nginx-ssl"
            port: 443
            monitored: true

    production:
      children:
        webservers:
        databases:
        proxies:
      vars:
        deployment_env: production
        alert_thresholds:
          cpu: 80
          memory: 85
          disk: 90
        backup_enabled: true